---
# tasks file for webserver
    - name: Instala Dependencias
      apt: 
        name:
          - php5
          - apache2
          - libapache2-mod-php5
          - php5-gd
          - libssh2-php
          - php5-mcrypt
          - php5-mysql
        state: latest
        update_cache: yes
      become: yes


